list2env(readr::read_rds("testingdat.rds"), envir = environment())
Yarray_x = aperm(Yarray, c(2,3,1))
nlimit <- c(.Machine$double.xmin, .Machine$double.xmax)^(1/3)
Rcpp::sourceCpp("joing_funs_dh_testing.cpp")
nll_fun(inits, X1, X2, tau_params, nsurvey, Yarray_x, tarray, rarray, nrint, ntint, max_r, Ysum, nlimit )
